title: Devlog
author: Joel Schutz
remote_theme: riggraz/no-style-please
post_search: true

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "../" # customize text for homepage link in post layout
  date_format: "%b-%d-%Y" # customize how date is formatted

sass:
  style: :compressed

plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag